version: '3.8'

volumes:
  postgres_data: {}


services:

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7
    ports:
      - 6379:6379

  app:
    image: app
    build:
        context: .
        dockerfile: docker/Dockerfile
    restart: "unless-stopped"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: gunicorn -c gunicorn_config.py main.asgi:application
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  frontend:
    image: app
    build:
        context: .
        dockerfile: docker/Dockerfile
    restart: "unless-stopped"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: streamlit run streamlit_app.py
    ports:
      - 8501:8501
