volumes:
  postgres_data: {}


services:

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  backend:
    image: backend
    build:
        context: backend
        dockerfile: docker/Dockerfile
    restart: "unless-stopped"
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env
    command: python3 manage.py runserver 0.0.0.0:8080
    ports:
      - 8080:8080