# Generated by Django 5.1.4 on 2025-01-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
