# Generated by Django 5.1.4 on 2025-02-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrambot", "0002_telegrambot_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="chat_id",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
