# Generated by Django 5.1.4 on 2025-02-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrambot", "0003_alter_conversation_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambot",
            name="log_conversation",
            field=models.BooleanField(default=True),
        ),
    ]
