# Generated by Django 5.1.5 on 2025-02-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrambot", "0005_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambot",
            name="about",
            field=models.TextField(blank=True, help_text="Text shown in bot's about section"),
        ),
        migrations.AddField(
            model_name="telegrambot",
            name="description",
            field=models.TextField(blank=True, help_text="Bot description shown in Telegram"),
        ),
        migrations.AddField(
            model_name="telegrambot",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="telegram_bot_photos/"),
        ),
        migrations.AddField(
            model_name="telegrambot",
            name="short_description",
            field=models.CharField(blank=True, help_text="Short description for bot profile", max_length=120),
        ),
        migrations.AddField(
            model_name="telegrambot",
            name="welcome_message",
            field=models.TextField(blank=True, help_text="Message sent when user starts the bot"),
        ),
    ]
