# Generated by Django 5.1.5 on 2025-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrambot", "0006_telegrambot_about_telegrambot_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegrambot",
            name="about",
        ),
        migrations.RemoveField(
            model_name="telegrambot",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="telegrambot",
            name="welcome_message",
        ),
        migrations.AddField(
            model_name="telegrambot",
            name="bot_specific_prompt",
            field=models.TextField(
                blank=True, help_text="Prompt which will be added to extend agent prompt to be more user-specific"
            ),
        ),
        migrations.AlterField(
            model_name="telegrambot",
            name="description",
            field=models.TextField(blank=True, help_text="Bot description shown in Telegram", max_length=512),
        ),
    ]
