# Generated by Django 5.1.5 on 2025-02-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrambot", "0007_remove_telegrambot_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(default="new", max_length=50),
        ),
    ]
