# Generated by Django 5.1.5 on 2025-03-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrambot", "0008_alter_lead_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambot",
            name="redirect_media_chat_id",
            field=models.CharField(
                blank=True, help_text="Chat ID where media messages will be redirected", max_length=50, null=True
            ),
        ),
    ]
