# Generated by Django 5.1.5 on 2025-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrambot", "0009_telegrambot_redirect_media_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambot",
            name="parse_mode",
            field=models.CharField(
                choices=[("MARKDOWN", "Markdown"), ("MARKDOWN_V2", "MarkdownV2"), ("HTML", "HTML"), (None, "None")],
                default="HTML",
                max_length=50,
                null=True,
            ),
        ),
    ]
