# Generated by Django 5.1.5 on 2025-03-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrambot", "0010_telegrambot_parse_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambot",
            name="parse_mode",
            field=models.CharField(
                blank=True,
                choices=[("Markdown", "Markdown"), ("MarkdownV2", "MarkdownV2"), ("HTML", "HTML"), (None, "None")],
                default="HTML",
                max_length=50,
                null=True,
            ),
        ),
    ]
