# Generated by Django 5.1.4 on 2024-12-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_instruction', models.TextField(default='You are a helpful personal assistant.', help_text='This is the instruction that the AI will use to generate responses.', verbose_name='System Instruction')),
                ('provider', models.CharField(default='openai', help_text='The provider that the AI will use to generate responses.', max_length=255, verbose_name='Provider')),
                ('model', models.CharField(default='gpt-4o', help_text='The model that the AI will use to generate responses.', max_length=255, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'LLM Provider Configuration',
            },
        ),
    ]
