# Generated by Django 5.1.4 on 2024-12-08 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'LLModel',
                'verbose_name_plural': 'LLModels',
            },
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llmanager.llmodel')),
            ],
            options={
                'verbose_name': 'LLMProvider',
                'verbose_name_plural': 'LLMProviders',
            },
        ),
    ]
